### ISSUE TITLE
Error: Pinecone Router: route already exist 

### ISSUE THREAD

**Issue by xiaoke4869** [pinecone-router/router#14]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/27657982/222459574-bce36f7e-d07c-4819-881a-7a93aa349f31.png">

I did not use others 'route' or 'router' in my project.

**Comment by rehhouari** [comment]
Hello, sorry for the inconvenience!
That errors is thrown when:
1. you use `x-route` attribute and specifiy a route that already exists
2. you call the `window.PineconeRouter.add()` method with a route that already exists

Can you share a reproduction example or something that can help debugging this?
