### ISSUE TITLE
Documentation for event listener

### ISSUE THREAD

**Issue by thbley** [pinecone-router/router#25]
**Describe the bug**
document.body.addEventListener() should be document.addEventListener() in README.md ?

**To Reproduce**

README.md has:
	document.body.addEventListener('pinecone-start', () => NProgress.start());
	document.body.addEventListener('pinecone-end', () => NProgress.done());

index.ts has:
	const startLoading = () => {
		document.dispatchEvent(PineconeRouter.loadStart)
...
	const endLoading = () => {
		document.dispatchEvent(PineconeRouter.loadEnd)

**Comment by rehhouari** [comment]
Wow issues close automatically when you reference it in a pull request!
Thanks for submitting this I missed it when I was updating!
