### ISSUE TITLE
fetch-error event not triggered for 404, 500 responses

### ISSUE THREAD

**Issue by thbley** [pinecone-router/router#26]
**Describe the bug**
fetch-error event not triggered for 404, 500 responses

**To Reproduce**
`<template x-route="/tasks/somewhere" x-template="http://invalid.local/foo.html"></template>`
triggers fetch-error event but also raises Uncaught TypeError: node is null
    addScopeToNode https://cdn.skypack.dev/-/alpinejs@v3.13.3-tmXwd9f1nfkJEXw67weg/dist=es2019,mode=imports/optimized/alpinejs.js:354

`<template x-route="/tasks/somewhere" x-template="/invalid.local"></template>`
does not trigger fetch-error event

**Expected behavior**
Both examples should trigger fetch-error event.
Maybe check for response.ok when calling fetch?
Both examples should not trigger Uncaught TypeError: node is null

**Desktop (please complete the following information):**
 - Kubuntu
 - Firefox 121
 - pinecone-router 4.0.0

**Additional context**

**Comment by rehhouari** [comment]
Looks like I didn't even a catch for the fetch statement, it was for the async function that had the fetch call 🤦 
I'll see what I can do thanks!

**Comment by rehhouari** [comment]
Let me know if the problem still persists!
I'd like to note despite using a catch, the eror still shows in console for some reason... however the event is dispatched too.
Also, when the fetch fails, the next time the route is visisted it will attempt to refetch, always.

**Comment by thbley** [comment]
I successfully verified the fix with v4.0.2, thank you!
