### ISSUE TITLE
x-if overrides x-route in template tag

### ISSUE THREAD

**Issue by thbley** [pinecone-router/router#27]
When I combine x-route with x-if, the x-route condition gets ignored.

**To Reproduce**

```
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/pinecone-router@4.x.x/dist/router.min.js"></script>
	<script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body>
    <div x-data>
        <a href="./hello/name">Tasks</a>
        <template x-if="true" x-route="./hello/name">
            <div>Hello!</div>
        </template>
    </div>
</body>
</html>
```
Gives output "Tasks Hello!" instead of "Tasks" although x-route does not match the current url.

----

```
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/pinecone-router@4.x.x/dist/router.min.js"></script>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body>
    <div x-data>
        <a href="./hello/name">Tasks</a>
        <template x-route="./hello/name">
            <div>Hello!</div>
        </template>
    </div>
</body>
</html>
```
Gives output "Tasks" since x-route does not match current url.

**Expected behavior**

When using x-route="url" together with x-if="expression", then the result should be:
```
x-if="(expression && $router.route == url && PineconeRouter.routes[0].handlersDone)".
```

My use case is this:
```
<template x-route="/tasks/create" x-if="$app.pageStore.loggedin">
```

Currently I use this workaround:
```
<template x-route="/tasks/create" x-if="$router.route === '/tasks/create' && $app.pageStore.loggedin">
```

**Desktop (please complete the following information):**
 - Kubuntu
 - Firefox 121

**Additional context**

**Comment by rehhouari** [comment]
Hey, adding the custom expression to the x-if sounds do-able, even tho today i rewrote the rendering system to replicate the functionality of x-if rather than add an `x-if` attribute.
I'll see if i can add this feature in any of the two implementations.

As for your use case, this looks like a job for [`x-handler`](https://github.com/pinecone-router/router#x-handler)
```html
<template x-route="..." x-handler="authChecker">
```
```js
function authChecker(ctx) {
  if (!$app.pageStore.loggedin) {
    return ctx.redirect('/login');
  }
}
```

Notice I returned `ctx.redirect` this will prevent templates from rendering and further handlers from executing if present (`x-handler="[authCheck, doSomething]"`)

**Comment by thbley** [comment]
with 4.1.0, x-if expression is ignored using:
```
<template x-route="/tasks/create" x-if="$router.route === '/tasks/create' && $app.pageStore.loggedin">
```
before 4.1.0, x-if was used instead of x-route.

**Comment by thbley** [comment]
Before 4.1.0, I used:
```
<template x-route="notfound">
    <load-template src="/tasks/templates/404.html"></load-template>
</template>
<template x-if="$router.route !== 'notfound' && !$app.pageStore.loggedin">
    <load-template src="/tasks/templates/login.html"></load-template>
</template>
<template x-route="/tasks/create" x-if="$router.route === '/tasks/create' && $app.pageStore.loggedin">
    <load-template src="/tasks/templates/tasks_create.html"></load-template>
</template>
```

With 4.1.0, I need to use:
```
<template x-route="notfound">
    <load-template src="/tasks/templates/404.html"></load-template>
</template>
<template x-if="$router.route !== 'notfound' && !$app.pageStore.loggedin">
    <load-template src="/tasks/templates/login.html"></load-template>
</template>
<template x-route="/tasks/create" x-handler="() => !$app.pageStore.loggedin ? 'stop' : ''">
    <load-template src="/tasks/templates/tasks_create.html"></load-template>
</template>
```

My preference would be more simple code, e.g.
```
<template x-route="/tasks/create" x-if="$app.pageStore.loggedin">
```

**Comment by rehhouari** [comment]
```html
<template x-route="notfound">
    <load-template src="/tasks/templates/404.html"></load-template>
</template>
<!-- there should be no need to check if the route is notfound, if it matches /login then it is found -->
<template x-route="/login" x-handler="authChecker">
    <load-template src="/tasks/templates/login.html"></load-template>
</template>
<template x-route="/tasks/create" x-handler="authChecker">
    <load-template src="/tasks/templates/tasks_create.html"></load-template>
</template>
<!-- this page doesn't have an authChecker so it doesn't care about authentication -->
<template x-route="/about">
    <load-template src="/tasks/templatesabout.html"></load-template>
</template>
```

```js
// most likely you'd put this in the component data
function authChecker(ctx) {
  // if you have a sign up route too then do:
  // ['login','signup'].includes(ctx.route)
  // all other pages need authentication which is usually the case
  // if the page doesn't care about authentication don't give it the handler
  if (ctx.route == 'login') {
    if ($app.pageStore.loggedin) return ctx.redirect('/tasks')
  } else if (!$app.pageStore.loggedin) return ctx.redirect('login')
}
```

this is as clean as it's gonna get without implementation of `x-if` and you'll only have to define authChecker once.

x-if sound good for extra conditional of the route, tho i think i can't implement it because x-if would still render the pages when you're logged in whether the route is matched or not, i'd have to remove the attribute's content and it add it to the route, then check it when the route is visited.

however it seems possible having another directive with this purpose such as `x-auth`. maybe it can be implemented externally using a middleware. I'll look into that

**Comment by rehhouari** [comment]
Btw with this handler method, before redirecting to the login page, you can save that page that is now unaccessible using `this.goBackToOnLogin = ctx.path` then in the login page when the user logins check if it is defined then redirect to it. gotta make sure to clear it, likely in the login handler or anytime after for example in authChecker if logged in and it exist it is safe to clear it.

**Comment by thbley** [comment]
Thanks for the feedback, I'll check what's the best strategy.
