### ISSUE TITLE
Layout got broken with 4.1

### ISSUE THREAD

**Issue by Huehnergott** [pinecone-router/router#28]
With v4.0.x pinecone we were using this to render a template inside a div with id `app`

`<template x-route="/" x-template.target.app="/pages/admin_dashboard.html"></template>`

It worked like a charme. 
Now everything gets renderd "in place" maeaning, exactly where the above template is defined.

Did you change any keywords again, like from 3.x.x to 4.x.x?

**Comment by rehhouari** [comment]
I thought I fixed this issue I'm sorry, I can reproduce it and I'll get a fix up ASAP.
for now you should be safe to use the previous version. I'll reply when I have updated

**Comment by rehhouari** [comment]
Hello, I have fixed the issue in 4.1.1.
Also, I'm currently working on allowing .target modifier to work on inline templates (`x-route.target.app`)
and thus I made it so the global setting `window.PineconeRouter.settings.templateTargetId` also applies to it by default when set.
If you have any objection let me know!

**Comment by Huehnergott** [comment]
Thx alot for the prompt fix. Seems to work now as it did before.
