### ISSUE TITLE
x-data and x-init doesn't fire off between parameter changes

### ISSUE THREAD

**Issue by taylordwright44** [pinecone-router/router#32]
I'm currently using x-data to create a users variable then x-init to fetch to the user data like the picture I uploaded. When I change routes, the data reloads normally, HOWEVER when I change routes from parameter to parameter (for example from localhost:3000/users/1 to localhost:3000/users/2 the data does not change. This is a bit of a problem as the template will look unchanged when a user swaps routes from parameter to parameter.

Is there a proper method to get around this, or this this just a bug?

![image](https://github.com/pinecone-router/router/assets/11287407/0da4f279-201a-428b-b21b-c1fd6290eb43)

**Comment by rehhouari** [comment]
Hey thanks for the issue!
Since it's the same route with different parameters, the template doesn't reload, thus the `x-init` code doesn't run again. I don't think that's a bug.

To do what you want, have you tried using [`x-handler`](https://github.com/pinecone-router/router#x-handler) next to `x-route`?

Let me know how it goes and sorry for the late response I wasn't online.

**Comment by rehhouari** [comment]
No worries and I'll consider reloading the template on param change if I could figure it out. Maybe make it a setting. On a second thought it sound reasonable and useful.

**Comment by taylordwright44** [comment]
> No worries and I'll consider reloading the template on param change if I could figure it out. Maybe make it a setting. On a second thought it sound reasonable and useful.

That'd be useful. That's one of the reasons I hated Angular is param changes being so complicated. I'm testing your earlier suggestions now.

**Comment by taylordwright44** [comment]
You were 100% correct, all I had to do was use the x-handler="[awaitedHandler]" from your demo code next to the x-route with the params and it fixed the issue. Thank you for the response.
