### ISSUE TITLE
Support for Page Transition

### ISSUE THREAD

**Issue by yllumi** [pinecone-router/router#43]
**Is your feature request related to a problem? Please describe.**
I want to implement page transitions in the Pinecone router. A great example can be seen in Framework7, where it displays the new page with animation and keeps the old page behind the active one when navigating back to the previous page.
This is possible if we don't remove the previous page but instead manage the page stack, allowing transitions between pages to happen smoothly. However, in the Pinecone router, the page transition is done by removing the old page and displaying elements from the new one.

**Describe the solution you'd like**
Can the Pinecone router manage a stack of page elements like that, so that we can implement smooth transition animations when moving to another page or returning to the previous one? Or is there any other solution for implementing page transition?

**Comment by rehhouari** [comment]
Hi! Sorry for the late reply
As for suggestions have you tried using a middleware? it hooks into router at certain points you could potentially implement your own page loading and transition through it?

as for implementing it on the router itself its not planned and I'm busy lately so I cannot give it a try on my own sorry.
Hope you figure it out!
